# Generated by Django 3.0.6 on 2020-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('representative', 'REPRESENTATIVE'), ('student', 'STUDENT')], default='student', max_length=20),
        ),
    ]
